---
title: "Regression"
author: "Eileen Blum"
date: "Last updated `r Sys.Date()`"
output: 
  html_document: 
    highlight: haddock
    theme: yeti
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Regression example

This is a simple bivariate regression example.


```{r}
2+2
```

```{r, my_setup, echo=TRUE, message=FALSE, warning=FALSE}
library(languageR)
library(tidyverse)
str(spanish)
```

##Tidy some data
Here we tidy the data

```{r, my_plot, warning=FALSE, fig.align='center', fig.width=10, fig.height=7}
my_data <- spanish %>%
  select(., x = X14461gll, y = X14473gll) %>%
  filter(., y < 0.06, x < 0.075)

  my_data %>%
  ggplot(., aes(x = x, y = y)) +
    geom_point() +
    geom_smooth(method = 'lm')
```

##Model
Here we fit a model.

```{r, my_model}
my_fit <- lm(y ~ x, data = my_data)
summary(my_fit)
```

```{r}
confint(my_fit)
```

The data where something 
Slope: `r coefficients(my_fit)[2]`, CI: LB: `r confint(my_fit)[1, c(1,2)]`

```{r}
coefficients(my_fit)
```

```{r}
#test normality of residuals
hist(residuals(my_fit))
qqnorm(residuals(my_fit))
qqline(residuals(my_fit))
```

##Tidy more data
```{r, my_plot2, warning=FALSE, fig.align='center', fig.width=10, fig.height=7}
my_data2 <- spanish %>%
  select(., x = X14474gll, y = X14462gll) %>%
  filter(., y < 0.06, x < 0.075)

  my_data2 %>%
  ggplot(., aes(x = x, y = y)) +
    geom_point() +
    geom_smooth(method = 'lm')
```

##Model 2
```{r, my_model2}
my_fit2 <- lm(y ~ x, data = my_data)
summary(my_fit2)
```

The data where something 
Slope: `r coefficients(my_fit2)[2]`, CI: LB: `r confint(my_fit2)[1, c(1,2)]`

```{r}
coefficients(my_fit2)
```

```{r}
#test normality of residuals
hist(residuals(my_fit2))
qqnorm(residuals(my_fit2))
qqline(residuals(my_fit2))
```